/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ConstructionCompanyWorkArea;

import Business.MunicipalCorporation.MunicipalCorporation;
import Business.Organization.ConstructionCompanyOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class ConstructionCompanyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConstructionCompanyWorkAreaJPanel
     */
    private JPanel userProcessContainer; 
    private UserAccount account; 
    private ConstructionCompanyOrganization organization;
    private MunicipalCorporation municipalCorporation;
    
    public ConstructionCompanyWorkAreaJPanel(JPanel userProcessContainer, 
            UserAccount account, ConstructionCompanyOrganization organization,
            MunicipalCorporation municipalCorporation) {
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.municipalCorporation=municipalCorporation;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBidding = new javax.swing.JButton();
        btnContract = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        btnBidding.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBidding.setText("Bidding Panel");
        btnBidding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiddingActionPerformed(evt);
            }
        });
        add(btnBidding);
        btnBidding.setBounds(280, 110, 192, 57);

        btnContract.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnContract.setText("Contract Panel");
        btnContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContractActionPerformed(evt);
            }
        });
        add(btnContract);
        btnContract.setBounds(280, 190, 192, 59);

        btnReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReport.setText("Predictive Analyzer");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        add(btnReport);
        btnReport.setBounds(280, 280, 192, 59);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBiddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiddingActionPerformed
        // TODO add your handling code here:
        BiddingJPanel bid=new BiddingJPanel(userProcessContainer, account, organization, municipalCorporation);
        userProcessContainer.add("BiddingJPanel",bid);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBiddingActionPerformed

    private void btnContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContractActionPerformed
        // TODO add your handling code here:
        ContractViewPanel cvp=new ContractViewPanel(userProcessContainer, account, organization, municipalCorporation);
        
        userProcessContainer.add("ContractViewPanel", cvp);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnContractActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        ReportJPanel rj=new ReportJPanel(userProcessContainer, account, organization, municipalCorporation);
        userProcessContainer.add("ReportJPanel", rj);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBidding;
    private javax.swing.JButton btnContract;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
