/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ConstructionCompanyWorkArea;

import Business.Email.EmailManagementSystem;
import Business.MunicipalCorporation.MunicipalCorporation;
import Business.Organization.ConstructionCompanyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CompanyContract;
import Business.WorkQueue.ContractRequest;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ContractViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContractViewPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private ConstructionCompanyOrganization organization;
    private MunicipalCorporation municipalCorporation;
    public ContractViewPanel(JPanel userProcessContainer,UserAccount account,
            ConstructionCompanyOrganization organization,MunicipalCorporation municipalCorporation) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.municipalCorporation=municipalCorporation;
        
        populateTable();
    }

    public void populateTable(){
        
        DefaultTableModel dtm=(DefaultTableModel)tblContract.getModel();
        dtm.setRowCount(0);
        
        for(ContractRequest request : organization.getWorkQueue().getContractList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1]=request.getCompany();
            row[2] = request.getArchitecture();
            row[3] = ((CompanyContract)request).getStatus();
            
            
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblContract = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnData = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        tblContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contract ID", "Company ", "Building", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblContract);

        add(jScrollPane1);
        jScrollPane1.setBounds(66, 59, 452, 92);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(70, 180, 110, 23);

        btnData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnData.setText("Process Contract");
        btnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActionPerformed(evt);
            }
        });
        add(btnData);
        btnData.setBounds(210, 180, 150, 23);

        btnStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnStatus.setText("Update Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        add(btnStatus);
        btnStatus.setBounds(370, 180, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contract.gif"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(240, 150, 500, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
        // TODO add your handling code here:
        
        int row=tblContract.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this, "Select a row");
            return;
        }
        ContractRequest contract=(CompanyContract)tblContract.getValueAt(row, 0);
        
        CompanyContract contract1=(CompanyContract)tblContract.getValueAt(row, 0);
        if(account==contract.getCompany()&&!contract1.getStatus().equals("Completed")){
            contract1.setStatus("Under Progress");
        
        EmailManagementSystem email=municipalCorporation.getEmail();
        
        String to=contract.getSender().getPerson().getEmailID();
        String subject="Contract Request Under Process";
        String Body="Contract is now under Process";
        
        try {
            email.GenerateMail(to, subject, Body);
        } catch (MessagingException ex) {
            
        }
        
        ProcessContractJPanel cvj=new ProcessContractJPanel(userProcessContainer,municipalCorporation,contract);
        userProcessContainer.add("ProcessContractJPanel", cvj);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            
            JOptionPane.showMessageDialog(this, "Contract not available");
        }
        
    }//GEN-LAST:event_btnDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
        int row=tblContract.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this, "Select a row");
            return;
        }
        
        CompanyContract contract1=(CompanyContract)tblContract.getValueAt(row, 0);
        contract1.setStatus("Completed");
        
        
        populateTable();
        ContractRequest contract=(CompanyContract)tblContract.getValueAt(row, 0);
        EmailManagementSystem email=municipalCorporation.getEmail();
        
        String to=contract.getSender().getPerson().getEmailID();
        String subject="Contract Completed";
        String Body="Reports and the Analysis have been uploaded to the system";
        
        try {
            email.GenerateMail(to, subject, Body);
        } catch (MessagingException ex) {
            
        }
        
        
        //Email
    }//GEN-LAST:event_btnStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContract;
    // End of variables declaration//GEN-END:variables
}
