/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ConstructionCompanyWorkArea;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.BidWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class PlaceBidsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlaceBidsJPanel
     */
    private JPanel userProcessContainer;
    private BidWorkRequest bid;
    private WorkRequest work;
    private UserAccount account;
    
    public PlaceBidsJPanel(JPanel userProcessContainer,BidWorkRequest bid,WorkRequest work,UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.bid=bid;
        this.work=work;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fldBidAmount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Company Bid Amount");
        add(jLabel1);
        jLabel1.setBounds(24, 44, 128, 22);
        add(fldBidAmount);
        fldBidAmount.setBounds(181, 44, 147, 20);

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(181, 94, 90, 23);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(60, 94, 100, 23);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bidding-websites-2.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //int highestLimit=work.getLowestBidAmount();
        try{
            int prevBidAmount=bid.getBidAmount();
            
            if(fldBidAmount.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Exception.Please enter valid amount",
                            "ERROR", JOptionPane.ERROR_MESSAGE);   
            
            }
            else{
                int curBidAmount=Integer.parseInt(fldBidAmount.getText());
        if (prevBidAmount!=0){
            if(curBidAmount<prevBidAmount){
                
                
                    bid.setBidAmount(curBidAmount);
                    work.setReceiver(account);
                
                
            }
            else{
                bid.setBidAmount(prevBidAmount);
            }
            
            
        }
        else
        {
           bid.setBidAmount(curBidAmount);
           work.setReceiver(account);
        }
            JOptionPane.showMessageDialog(this, "Bid Amount added to the system");
            fldBidAmount.setText("");

            }
            
            fldBidAmount.setText("");
                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Exception.Please enter valid amount",
                            "ERROR", JOptionPane.ERROR_MESSAGE);   
            
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BiddingJPanel ccw = (BiddingJPanel) component;
        ccw.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField fldBidAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
