/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ConstructionCompanyWorkArea;

import Business.MunicipalCorporation.MunicipalCorporation;
import Business.Organization.ConstructionCompanyOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    
    private JPanel userProcessContainer;
    private MunicipalCorporation municipalCorporation;
    private ConstructionCompanyOrganization organization;
    private UserAccount account;
    
    public ReportJPanel(JPanel userProcessContainer, 
            UserAccount account, ConstructionCompanyOrganization organization,
            MunicipalCorporation municipalCorporation) {
        
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.municipalCorporation=municipalCorporation;
        this.organization=organization;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalysis = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        btnAnalysis.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAnalysis.setText("Predictive Analysis");
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });
        add(btnAnalysis);
        btnAnalysis.setBounds(370, 250, 280, 80);

        btnReports.setBackground(new java.awt.Color(153, 153, 153));
        btnReports.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        add(btnReports);
        btnReports.setBounds(370, 110, 280, 80);

        btnBack.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(280, 390, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        ViewChartJPanel vcj=new ViewChartJPanel(userProcessContainer, account, organization, municipalCorporation);
        userProcessContainer.add("ViewChartJPanel", vcj);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:
        DecisionMakingJPanel ajp=new DecisionMakingJPanel(userProcessContainer, account, organization, municipalCorporation);
        userProcessContainer.add("ViewChartJPanel", ajp);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalysisActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
