/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdminWorkArea;

import Business.FedGoverment;
import Business.StateGoverment.StateGoverment;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageStateGovermentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStateGovermentJPanel
     */
    private JPanel userProcessContainer;
    private FedGoverment fedGoverment;
    
    public ManageStateGovermentJPanel(JPanel userProcessContainer,FedGoverment fedGoverment) {
        initComponents();
        this.fedGoverment=fedGoverment;
        this.userProcessContainer=userProcessContainer;
        
        populateTable();
        
    }
    
    public void populateTable(){
        
        DefaultTableModel dtm=(DefaultTableModel) stateTable.getModel();
        
        dtm.setRowCount(0);
        
        for(StateGoverment state:fedGoverment.getStateGovermentList()){
            
            Object row[]=new Object[1];
            
            row[0]=state.getName();
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stateTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtStateName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        stateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "State goverment List"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stateTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(80, 80, 190, 107);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("State Name :");
        add(jLabel1);
        jLabel1.setBounds(310, 80, 90, 24);

        txtStateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateNameActionPerformed(evt);
            }
        });
        add(txtStateName);
        txtStateName.setBounds(280, 110, 168, 24);

        btnBack.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(140, 210, 90, 25);

        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(320, 150, 90, 25);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 3, 14)); // NOI18N
        jLabel2.setText("StateGoverment Panel");
        add(jLabel2);
        jLabel2.setBounds(200, 20, 180, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/state.gif"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(90, 240, 400, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
       try{
        String name =txtStateName.getText();
        String Regex = "^[a-zA-Z]+$";
        
        if(!name.trim().matches(Regex)){
            JOptionPane.showMessageDialog(this, "Please enter a vlaid State name!!.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);   
            
        }
        else{
             StateGoverment state=fedGoverment.createAndAddStateGoverment();
        
        state.setName(name);
        
        JOptionPane.showMessageDialog(this,"New State Added to the System");
        populateTable();
        txtStateName.setText("");
       
        }
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter a vlaid State name!!.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);   
           
       }
        
    }//GEN-LAST:event_btnSubmitActionPerformed
   
    private void txtStateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stateTable;
    private javax.swing.JTextField txtStateName;
    // End of variables declaration//GEN-END:variables
}
