/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdminWorkArea;

import Business.MunicipalCorporation.MunicipalCorporation;
import Business.FedGoverment;
import Business.Organization.Organization;
import Business.StateGoverment.StateGoverment;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author User
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private FedGoverment fedGoverment;
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,FedGoverment fedGoverment) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.fedGoverment=fedGoverment;
        
        populateTree();
    }
    
    public void populateTree(){
        
        DefaultTreeModel model = (DefaultTreeModel) SystemTree.getModel();

        
        
        ArrayList<StateGoverment> stateGovermentList = fedGoverment.getStateGovermentList();
        ArrayList<MunicipalCorporation> departmentList;
        ArrayList<Organization> organizationList;
        StateGoverment stateGoverment;
        MunicipalCorporation department;
        Organization organization;

        DefaultMutableTreeNode stateGoverments = new DefaultMutableTreeNode("StateGoverments");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(stateGoverments, 0);

        DefaultMutableTreeNode stateGovermentNode;
        DefaultMutableTreeNode departmentNode;
        DefaultMutableTreeNode organizationNode;
        for (int i = 0; i < stateGovermentList.size(); i++) {
            stateGoverment = stateGovermentList.get(i);
            stateGovermentNode = new DefaultMutableTreeNode(stateGoverment.getName());
            stateGoverments.insert(stateGovermentNode, i);

            departmentList = stateGoverment.getMunicipalCorporationDirectory().getMunicipalCorporationList();

            for (int j = 0; j < departmentList.size(); j++) {
                department = departmentList.get(j);
                departmentNode = new DefaultMutableTreeNode(department.getName());
                stateGovermentNode.insert(departmentNode, j);

                organizationList = department.getOrganizationDirectory().getOrganizationList();
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    departmentNode.insert(organizationNode, k);
                }
            }
        }

        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SystemTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        btnManageStateGoverment = new javax.swing.JButton();
        btnManageDepartment = new javax.swing.JButton();
        btnDeptAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jSplitPane1.setDividerLocation(130);

        SystemTree.setBackground(new java.awt.Color(153, 153, 248));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Federal Goverment");
        SystemTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(SystemTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(null);

        btnManageStateGoverment.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageStateGoverment.setText("Manage State Goverment");
        btnManageStateGoverment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStateGovermentActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageStateGoverment);
        btnManageStateGoverment.setBounds(330, 140, 240, 70);

        btnManageDepartment.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageDepartment.setText("Manage Municipal Corporation");
        btnManageDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDepartmentActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageDepartment);
        btnManageDepartment.setBounds(330, 250, 240, 70);

        btnDeptAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnDeptAdmin.setText("Manage MC Admin");
        btnDeptAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeptAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeptAdmin);
        btnDeptAdmin.setBounds(330, 370, 240, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysadmin.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 800);

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStateGovermentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStateGovermentActionPerformed
        // TODO add your handling code here:
        ManageStateGovermentJPanel msg=new ManageStateGovermentJPanel(userProcessContainer, fedGoverment);
        userProcessContainer.add("Manage State Goverment", msg);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStateGovermentActionPerformed

    private void btnManageDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDepartmentActionPerformed
        // TODO add your handling code here:
        ManageMunicipalCorpJPanel mdj=new ManageMunicipalCorpJPanel(userProcessContainer, fedGoverment);
        
        userProcessContainer.add("Manage Department", mdj);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDepartmentActionPerformed

    private void btnDeptAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptAdminActionPerformed
        // TODO add your handling code here:
        MunicipalCorpAdminJPanel dpa=new MunicipalCorpAdminJPanel(userProcessContainer, fedGoverment);
        
        userProcessContainer.add("Dept Admin", dpa);
        
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDeptAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree SystemTree;
    private javax.swing.JButton btnDeptAdmin;
    private javax.swing.JButton btnManageDepartment;
    private javax.swing.JButton btnManageStateGoverment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
