/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.MunicipalCorpAdminWorkArea;

import Business.Email.EmailManagementSystem;
import Business.FedGoverment;
import Business.MunicipalCorporation.MunicipalCorporation;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageEntityLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEntityLoginJPanel
     */
    private JPanel userProcessContainer;
    private MunicipalCorporation municipalCorp;
    
    public ManageEntityLoginJPanel(JPanel userProcessContainer,MunicipalCorporation municipalCorp) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.municipalCorp=municipalCorp;
        
        populateTable();
        populateOrganizationCombo();
    }

    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) systemTable.getModel();

        model.setRowCount(0);

        for (Organization organization : municipalCorp.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = organization;
                row[1] = ua;
                ((DefaultTableModel) systemTable.getModel()).addRow(row);
            }
        }
    }
    
    public void populateOrganizationCombo(){
        
        organizationCombo.removeAllItems();

        for (Organization organization : municipalCorp.getOrganizationDirectory().getOrganizationList()) {
            if(organization!=null){
                organizationCombo.addItem(organization);
                btnSubmit.setEnabled(true);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        systemTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        organizationCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        personCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        roleCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        fldUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        systemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(systemTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 54, -1, 106));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel5.setText("Organization");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 199, -1, -1));

        organizationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationComboActionPerformed(evt);
            }
        });
        add(organizationCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 146, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setText("Person");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        add(personCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 227, 146, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setText("Role");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 256, 34, -1));

        add(roleCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 253, 146, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("User Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 284, -1, -1));
        add(fldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 284, 146, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 318, -1, -1));
        add(fldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 322, 146, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setEnabled(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void organizationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationComboActionPerformed
        Organization organization = (Organization) organizationCombo.getSelectedItem();
        if (organization != null){
            populatePerson(organization);
            populateRole(organization);
        }
    }//GEN-LAST:event_organizationComboActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try{
           String userName = fldUserName.getText();
        String password = String.valueOf(fldPassword.getPassword());
        String regEx="^[a-zA-Z0-9][0-9a-zA-Z .,'-]*$";
        Organization organization = (Organization) organizationCombo.getSelectedItem();
        Person person = (Person) personCombo.getSelectedItem();
        Role role = (Role) roleCombo.getSelectedItem();
        if(!userName.trim().matches(regEx)&&!password.trim().matches(regEx)){
            JOptionPane.showMessageDialog(this, "Please add correct data in the fields.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);   

        }
        else{
            organization.getUserAccountDirectory().createUserAccount(userName, password, person, role);
        
        EmailManagementSystem email=municipalCorp.getEmail();
        String to=person.getEmailID();
        String subject="Welcome!!";
        String body="Welcome to the system \n Your userName is "+userName;
        
        try {
            email.GenerateMail(to, subject, body);
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(this, "Error while sending the email ");
        }
        populateTable();
            
        } 
        JOptionPane.showMessageDialog(this, "UserName and Password added to the system.");
        fldPassword.setText("");
        fldUserName.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please add correct data in the fields.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);   

        }
       
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    public void populatePerson(Organization organization){
        personCombo.removeAllItems();
        
        for (Person person : organization.getPersonDirectory().getEmployeeList()){
            personCombo.addItem(person);
        }
    }
    
    public void populateRole(Organization organization){
        
        roleCombo.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            
            roleCombo.addItem(role);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JTextField fldUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationCombo;
    private javax.swing.JComboBox personCombo;
    private javax.swing.JComboBox roleCombo;
    private javax.swing.JTable systemTable;
    // End of variables declaration//GEN-END:variables
}
