/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.MunicipalCorpAdminWorkArea;

import Business.FedGoverment;
import Business.MunicipalCorporation.MunicipalCorporation;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class MunicipalCorpAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MunicipalCorpAdminWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private MunicipalCorporation municipalCorp;
    public MunicipalCorpAdminWorkAreaJPanel(JPanel userProcessContainer,MunicipalCorporation municipalCorp) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.municipalCorp=municipalCorp;
       // lblAccount.setText(municipalCorp.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrganization = new javax.swing.JButton();
        btnOrganizationEntity = new javax.swing.JButton();
        btnEntitytLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrganization.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnOrganization.setText("Manage Organization Panel");
        btnOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizationActionPerformed(evt);
            }
        });
        add(btnOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 124, 190, 40));

        btnOrganizationEntity.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnOrganizationEntity.setText("Manage Organization Entitity");
        btnOrganizationEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizationEntityActionPerformed(evt);
            }
        });
        add(btnOrganizationEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 190, 190, 40));

        btnEntitytLogin.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnEntitytLogin.setText("Manage Entity LogIn");
        btnEntitytLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntitytLoginActionPerformed(evt);
            }
        });
        add(btnEntitytLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 190, 40));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("MUNICIPAL CORPORATION ADMIN WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 500, 33));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrator-clipart-sysadmin.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel moj=new ManageOrganizationJPanel(userProcessContainer, municipalCorp.getOrganizationDirectory());
        userProcessContainer.add("ManageOrganizationJPanel", moj);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrganizationActionPerformed

    private void btnOrganizationEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationEntityActionPerformed
        // TODO add your handling code here
        ManageOrganizationEnitityJPanel moe=new ManageOrganizationEnitityJPanel(userProcessContainer, municipalCorp.getOrganizationDirectory());
        
        userProcessContainer.add("ManageOrganizationEnitityJPanel", moe);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrganizationEntityActionPerformed

    private void btnEntitytLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntitytLoginActionPerformed
        // TODO add your handling code here:
        ManageEntityLoginJPanel mel=new ManageEntityLoginJPanel(userProcessContainer, municipalCorp);
        userProcessContainer.add("ManageEntityLoginJPanel", mel);
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEntitytLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntitytLogin;
    private javax.swing.JButton btnOrganization;
    private javax.swing.JButton btnOrganizationEntity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
