/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.MunicipalCommisionerWorkArea;

import Business.MunicipalCorporation.MunicipalCorporation;
import Business.Organization.MunicipalCommsionerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class ReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportsJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private MunicipalCommsionerOrganization mco;
    private MunicipalCorporation municipalCorporation;
    
    
    public ReportsJPanel(JPanel userProcessContainer,UserAccount account,
            MunicipalCommsionerOrganization mco,MunicipalCorporation municipalCorporation) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.municipalCorporation=municipalCorporation;
        this.mco=mco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheckStatus = new javax.swing.JButton();
        btnUnsafe = new javax.swing.JButton();
        btnAudit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnCheckStatus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCheckStatus.setText("Check Status");
        btnCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStatusActionPerformed(evt);
            }
        });
        add(btnCheckStatus);
        btnCheckStatus.setBounds(165, 51, 162, 52);

        btnUnsafe.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUnsafe.setText("Unsafe Architectures");
        btnUnsafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnsafeActionPerformed(evt);
            }
        });
        add(btnUnsafe);
        btnUnsafe.setBounds(165, 130, 162, 56);

        btnAudit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAudit.setText("Corporation Audit");
        btnAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditActionPerformed(evt);
            }
        });
        add(btnAudit);
        btnAudit.setBounds(165, 220, 162, 52);

        btnBack.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(61, 303, 81, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Monthly-Reports.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStatusActionPerformed
        // TODO add your handling code here:
        CheckStatusJPanel csj=new CheckStatusJPanel(userProcessContainer, account, mco, municipalCorporation);
        
        userProcessContainer.add("CheckStatusJPanel", csj);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckStatusActionPerformed

    private void btnUnsafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnsafeActionPerformed
        // TODO add your handling code here:
        UnsafeArchitectureJPanel uaj=new UnsafeArchitectureJPanel(userProcessContainer, account, mco, municipalCorporation);
        userProcessContainer.add("UnsafeArchJPanel", uaj);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUnsafeActionPerformed

    private void btnAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditActionPerformed
        // TODO add your handling code here:
        AuditJPanel audit=new AuditJPanel(userProcessContainer, account, mco, municipalCorporation);
        userProcessContainer.add("AuditJPanel", audit);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnAuditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAudit;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckStatus;
    private javax.swing.JButton btnUnsafe;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
