/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CitizenWorkArea;

import Business.FedGoverment;
import Business.MunicipalCorporation.MunicipalCorporation;
import Business.Organization.CitizenOrganization;
import Business.Organization.MunicipalCommsionerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class CitizenWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CitizenWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private CitizenOrganization mco;
    private MunicipalCorporation municipalCorporation;
    private FedGoverment fedGoverment;
    
    public CitizenWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,
            CitizenOrganization mco,MunicipalCorporation municipalCorporation,FedGoverment fedGoverment) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.municipalCorporation=municipalCorporation;
        this.mco=mco;
        this.fedGoverment=fedGoverment;
        
        lblAccount.setText(account.getPerson().getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUnsafe = new javax.swing.JButton();
        btnAccess = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnUnsafe.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUnsafe.setText("Unsafe Architectures in the City");
        btnUnsafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnsafeActionPerformed(evt);
            }
        });
        add(btnUnsafe);
        btnUnsafe.setBounds(131, 187, 272, 38);

        btnAccess.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAccess.setText("Access Municipal Corporation Projects");
        btnAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessActionPerformed(evt);
            }
        });
        add(btnAccess);
        btnAccess.setBounds(131, 109, 272, 42);

        btnCheck.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCheck.setText("Check your Buidling Safety Ranking");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        add(btnCheck);
        btnCheck.setBounds(131, 260, 272, 43);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Welcome ");
        add(jLabel1);
        jLabel1.setBounds(37, 51, 64, 31);

        lblAccount.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        add(lblAccount);
        lblAccount.setBounds(119, 51, 124, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Monthly-Reports.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(50, 60, 620, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessActionPerformed
        // TODO add your handling code here:
        AccessMunicipalCorpProjects amc=new AccessMunicipalCorpProjects(userProcessContainer, account, mco, municipalCorporation, fedGoverment);
        
        userProcessContainer.add("AccessMunicipalCorpProjects", amc);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAccessActionPerformed

    private void btnUnsafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnsafeActionPerformed
        // TODO add your handling code here:
        UnsafeArchJPanel uaj=new UnsafeArchJPanel(userProcessContainer, account, mco, municipalCorporation);
        userProcessContainer.add("UnsafeArchJPanel", uaj);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUnsafeActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        
       
        BuildigSafetyRankingJPanel bsr=new BuildigSafetyRankingJPanel(userProcessContainer, account, mco, municipalCorporation);
        userProcessContainer.add("BuildigSafetyRankingJPanel",bsr);
        
       // sample s = new sample();
        //userProcessContainer.add("ddf",s);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccess;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnUnsafe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAccount;
    // End of variables declaration//GEN-END:variables
}
