/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CitizenWorkArea;

import Business.Architecture.Architecture;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class ViewMoreInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMoreInfoJPanel
     */
    private JPanel userProcesscontainer;
    private Architecture architecture;
    
    public ViewMoreInfoJPanel(JPanel userProcesscontainer,Architecture architecture) {
        initComponents();
        this.userProcesscontainer=userProcesscontainer;
        this.architecture=architecture;
        
        displayFields();
    }
    public void displayFields(){
        
        fldName.setText(architecture.getArchitectureName());
        fldStatus.setText(architecture.getStatus());
        fldTime.setText(String.valueOf(architecture.getRepairDays()));
        txtComments.setText(architecture.getComments());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fldStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fldTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Building Name : ");
        add(jLabel1);
        jLabel1.setBounds(55, 54, 120, 26);

        fldName.setEditable(false);
        add(fldName);
        fldName.setBounds(230, 60, 152, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Building Status:");
        add(jLabel2);
        jLabel2.setBounds(55, 98, 130, 26);

        fldStatus.setEditable(false);
        add(fldStatus);
        fldStatus.setBounds(230, 100, 152, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Estimated Time for Repair:");
        add(jLabel3);
        jLabel3.setBounds(55, 142, 170, 28);

        fldTime.setEditable(false);
        add(fldTime);
        fldTime.setBounds(230, 150, 152, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Repair Comments :");
        add(jLabel4);
        jLabel4.setBounds(55, 188, 123, 28);

        txtComments.setEditable(false);
        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane1.setViewportView(txtComments);

        add(jScrollPane1);
        jScrollPane1.setBounds(230, 190, 166, 96);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(65, 243, 73, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Building-information-management-in-BIM-environment.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(310, 0, 610, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcesscontainer.remove(this);
        
        CardLayout layout=(CardLayout)userProcesscontainer.getLayout();
        layout.previous(userProcesscontainer);
                
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField fldName;
    private javax.swing.JTextField fldStatus;
    private javax.swing.JTextField fldTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtComments;
    // End of variables declaration//GEN-END:variables
}
